# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('posting_ip', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
            ],
            options={
                'permissions': [('can_edit_comment_settings', 'Can edit comment settings')],
            },
        ),
        migrations.CreateModel(
            name='IPLockout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=64)),
                ('locked_until', models.DateTimeField()),
                ('reason', models.CharField(max_length=256)),
            ],
        ),
    ]
